### ISSUE TITLE
README.md with doubled content

### ISSUE THREAD

**Issue by nervaccio** [driftphp/docs#3]
is it a dejavu in "Matrix" or README.md presents two times the same content?

Great work btw!

**Comment by mmoreram** [comment]
What do you mean?
Docs are generated by the README content.
Is there anything I'm missing?

Thanks :)

**Comment by nervaccio** [comment]
Hi!
It's easier that I'm bad to examplain the "problem"!

I mean when i view the documentation/README.md at: [https://github.com/driftphp/docs](https://github.com/driftphp/docs)

I see that there is two times the documentation: [https://imgur.com/a/vE48Oj9](https://imgur.com/a/vE48Oj9)

:D I hope it's much clear

**Comment by mmoreram** [comment]
You're totally right.
I'll check this.

Thanks!

**Comment by mmoreram** [comment]
@nervaccio fixed, thanks :D
